locations:
  - DANISMA
  - TEKNOLOJI
  - ROMAN
  - OKUMA
  - YENI_CIKANLAR

DANISMA:
  goal: {x: -0.70679, y: 5.0264, yaw: 0.160657}
  qr_expected: "LOC=DANISMA_MASASI"

TEKNOLOJI:
  goal: {x: -0.74578, y: -1.5736, yaw: -1.260829}
  qr_expected: "LOC=TEKNOLOJI_STANDI"

ROMAN:
  goal: {x: 6.6371, y: 0.53398, yaw: 0.012323}
  qr_expected: "LOC=ROMAN_BOLUMU"

OKUMA:
  goal: {x: -5.2959, y: -3.7372, yaw: -2.985271}
  qr_expected: "LOC=OKUMA_MASASI"

YENI_CIKANLAR:
  goal: {x: 0.51707, y: -5.8475, yaw: -1.633661}
  qr_expected: "LOC=YENI_CIKANLAR"
